// Copyright 2025 (c) By Rick Wesson & Support Intelligence, Inc.
// Licenced under the RLL 1.0
// protoc --go_out=.  --go-grpc_out=. holloman.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: holloman.proto

package holloman

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acceleration  string                 `protobuf:"bytes,10,opt,name=Acceleration,proto3" json:"Acceleration,omitempty"`
	MaxOrder      int32                  `protobuf:"varint,20,opt,name=MaxOrder,proto3" json:"MaxOrder,omitempty"`
	Magic         string                 `protobuf:"bytes,30,opt,name=Magic,proto3" json:"Magic,omitempty"`
	Ssdeep        bool                   `protobuf:"varint,40,opt,name=Ssdeep,proto3" json:"Ssdeep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceCapabilities) Reset() {
	*x = ServiceCapabilities{}
	mi := &file_holloman_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCapabilities) ProtoMessage() {}

func (x *ServiceCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_holloman_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCapabilities.ProtoReflect.Descriptor instead.
func (*ServiceCapabilities) Descriptor() ([]byte, []int) {
	return file_holloman_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceCapabilities) GetAcceleration() string {
	if x != nil {
		return x.Acceleration
	}
	return ""
}

func (x *ServiceCapabilities) GetMaxOrder() int32 {
	if x != nil {
		return x.MaxOrder
	}
	return 0
}

func (x *ServiceCapabilities) GetMagic() string {
	if x != nil {
		return x.Magic
	}
	return ""
}

func (x *ServiceCapabilities) GetSsdeep() bool {
	if x != nil {
		return x.Ssdeep
	}
	return false
}

type BufferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffer        []byte                 `protobuf:"bytes,10,opt,name=Buffer,proto3" json:"Buffer,omitempty"`
	Label         string                 `protobuf:"bytes,20,opt,name=Label,proto3" json:"Label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferRequest) Reset() {
	*x = BufferRequest{}
	mi := &file_holloman_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferRequest) ProtoMessage() {}

func (x *BufferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_holloman_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferRequest.ProtoReflect.Descriptor instead.
func (*BufferRequest) Descriptor() ([]byte, []int) {
	return file_holloman_proto_rawDescGZIP(), []int{1}
}

func (x *BufferRequest) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *BufferRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type BufferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HOrder        int32                  `protobuf:"varint,10,opt,name=HOrder,proto3" json:"HOrder,omitempty"`
	Len           int32                  `protobuf:"varint,15,opt,name=Len,proto3" json:"Len,omitempty"`
	Id            string                 `protobuf:"bytes,20,opt,name=Id,proto3" json:"Id,omitempty"`
	Magic         string                 `protobuf:"bytes,30,opt,name=Magic,proto3" json:"Magic,omitempty"`
	Ssdeep        string                 `protobuf:"bytes,40,opt,name=Ssdeep,proto3" json:"Ssdeep,omitempty"`
	Sha1          string                 `protobuf:"bytes,50,opt,name=Sha1,proto3" json:"Sha1,omitempty"`
	Label         string                 `protobuf:"bytes,60,opt,name=Label,proto3" json:"Label,omitempty"`
	Tlsh          string                 `protobuf:"bytes,70,opt,name=Tlsh,proto3" json:"Tlsh,omitempty"`
	Sdhash        string                 `protobuf:"bytes,80,opt,name=Sdhash,proto3" json:"Sdhash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferResponse) Reset() {
	*x = BufferResponse{}
	mi := &file_holloman_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferResponse) ProtoMessage() {}

func (x *BufferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_holloman_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferResponse.ProtoReflect.Descriptor instead.
func (*BufferResponse) Descriptor() ([]byte, []int) {
	return file_holloman_proto_rawDescGZIP(), []int{2}
}

func (x *BufferResponse) GetHOrder() int32 {
	if x != nil {
		return x.HOrder
	}
	return 0
}

func (x *BufferResponse) GetLen() int32 {
	if x != nil {
		return x.Len
	}
	return 0
}

func (x *BufferResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BufferResponse) GetMagic() string {
	if x != nil {
		return x.Magic
	}
	return ""
}

func (x *BufferResponse) GetSsdeep() string {
	if x != nil {
		return x.Ssdeep
	}
	return ""
}

func (x *BufferResponse) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *BufferResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BufferResponse) GetTlsh() string {
	if x != nil {
		return x.Tlsh
	}
	return ""
}

func (x *BufferResponse) GetSdhash() string {
	if x != nil {
		return x.Sdhash
	}
	return ""
}

var File_holloman_proto protoreflect.FileDescriptor

const file_holloman_proto_rawDesc = "" +
	"\n" +
	"\x0eholloman.proto\x12\bholloman\"\x83\x01\n" +
	"\x13ServiceCapabilities\x12\"\n" +
	"\fAcceleration\x18\n" +
	" \x01(\tR\fAcceleration\x12\x1a\n" +
	"\bMaxOrder\x18\x14 \x01(\x05R\bMaxOrder\x12\x14\n" +
	"\x05Magic\x18\x1e \x01(\tR\x05Magic\x12\x16\n" +
	"\x06Ssdeep\x18( \x01(\bR\x06Ssdeep\"=\n" +
	"\rBufferRequest\x12\x16\n" +
	"\x06Buffer\x18\n" +
	" \x01(\fR\x06Buffer\x12\x14\n" +
	"\x05Label\x18\x14 \x01(\tR\x05Label\"\xce\x01\n" +
	"\x0eBufferResponse\x12\x16\n" +
	"\x06HOrder\x18\n" +
	" \x01(\x05R\x06HOrder\x12\x10\n" +
	"\x03Len\x18\x0f \x01(\x05R\x03Len\x12\x0e\n" +
	"\x02Id\x18\x14 \x01(\tR\x02Id\x12\x14\n" +
	"\x05Magic\x18\x1e \x01(\tR\x05Magic\x12\x16\n" +
	"\x06Ssdeep\x18( \x01(\tR\x06Ssdeep\x12\x12\n" +
	"\x04Sha1\x182 \x01(\tR\x04Sha1\x12\x14\n" +
	"\x05Label\x18< \x01(\tR\x05Label\x12\x12\n" +
	"\x04Tlsh\x18F \x01(\tR\x04Tlsh\x12\x16\n" +
	"\x06Sdhash\x18P \x01(\tR\x06Sdhash2\x9c\x01\n" +
	"\bHolloman\x12L\n" +
	"\fCapabilities\x12\x1d.holloman.ServiceCapabilities\x1a\x1d.holloman.ServiceCapabilities\x12B\n" +
	"\rClusterBuffer\x12\x17.holloman.BufferRequest\x1a\x18.holloman.BufferResponseB\x14Z\x12main/iidf/hollomanb\x06proto3"

var (
	file_holloman_proto_rawDescOnce sync.Once
	file_holloman_proto_rawDescData []byte
)

func file_holloman_proto_rawDescGZIP() []byte {
	file_holloman_proto_rawDescOnce.Do(func() {
		file_holloman_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_holloman_proto_rawDesc), len(file_holloman_proto_rawDesc)))
	})
	return file_holloman_proto_rawDescData
}

var file_holloman_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_holloman_proto_goTypes = []any{
	(*ServiceCapabilities)(nil), // 0: holloman.ServiceCapabilities
	(*BufferRequest)(nil),       // 1: holloman.BufferRequest
	(*BufferResponse)(nil),      // 2: holloman.BufferResponse
}
var file_holloman_proto_depIdxs = []int32{
	0, // 0: holloman.Holloman.Capabilities:input_type -> holloman.ServiceCapabilities
	1, // 1: holloman.Holloman.ClusterBuffer:input_type -> holloman.BufferRequest
	0, // 2: holloman.Holloman.Capabilities:output_type -> holloman.ServiceCapabilities
	2, // 3: holloman.Holloman.ClusterBuffer:output_type -> holloman.BufferResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_holloman_proto_init() }
func file_holloman_proto_init() {
	if File_holloman_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_holloman_proto_rawDesc), len(file_holloman_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_holloman_proto_goTypes,
		DependencyIndexes: file_holloman_proto_depIdxs,
		MessageInfos:      file_holloman_proto_msgTypes,
	}.Build()
	File_holloman_proto = out.File
	file_holloman_proto_goTypes = nil
	file_holloman_proto_depIdxs = nil
}
