# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: holloman.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'holloman.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eholloman.proto\x12\x08holloman\"=\n\x13ServiceCapabilities\x12\x14\n\x0c\x41\x63\x63\x65leration\x18\n \x01(\t\x12\x10\n\x08MaxOrder\x18\x14 \x01(\x05\"\x1f\n\rBufferRequest\x12\x0e\n\x06\x42uffer\x18\n \x01(\x0c\"B\n\x0e\x42ufferResponse\x12\x0e\n\x06HOrder\x18\n \x01(\x05\x12\x11\n\tIdentifer\x18\x14 \x01(\x0c\x12\r\n\x05Magic\x18\x1e \x01(\t2\x9c\x01\n\x08Holloman\x12L\n\x0c\x43\x61pabilities\x12\x1d.holloman.ServiceCapabilities\x1a\x1d.holloman.ServiceCapabilities\x12\x42\n\rClusterBuffer\x12\x17.holloman.BufferRequest\x1a\x18.holloman.BufferResponseB\x14Z\x12main/iidf/hollomanb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'holloman_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022main/iidf/holloman'
  _globals['_SERVICECAPABILITIES']._serialized_start=28
  _globals['_SERVICECAPABILITIES']._serialized_end=89
  _globals['_BUFFERREQUEST']._serialized_start=91
  _globals['_BUFFERREQUEST']._serialized_end=122
  _globals['_BUFFERRESPONSE']._serialized_start=124
  _globals['_BUFFERRESPONSE']._serialized_end=190
  _globals['_HOLLOMAN']._serialized_start=193
  _globals['_HOLLOMAN']._serialized_end=349
# @@protoc_insertion_point(module_scope)
